import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import screener_client, valuation_engine, openpyxl

data = screener_client.fetch_company_data('ADANIENT')
val_res = valuation_engine.calculate_valuation(data)

print("=== VALUATION ENGINE INPUTS & INTERMEDIATES ===")
print("latest_ebit:", val_res.get('dcf_schedule', [{}])[0].get('ebit'))
print("eff_tax_rate / NOPAT Y1:", val_res.get('dcf_schedule', [{}])[0].get('nopat'))
print("Reinvest Y1:", val_res.get('dcf_schedule', [{}])[0].get('reinvestment_rate'))
print("FCFF Y1:", val_res.get('dcf_schedule', [{}])[0].get('fcff'))
print("FCFF Y5:", val_res.get('dcf_schedule', [{}])[-1].get('fcff'))
print("PV FCFF Sum:", val_res.get('pv_fcff_sum'))
print("Terminal Value:", val_res.get('terminal_value'))
print("PV Terminal Value:", val_res.get('pv_terminal_value'))
print("Enterprise Value:", val_res.get('enterprise_value'))
print("Total Debt:", val_res.get('total_debt'))
print("Cash Estimate:", val_res.get('cash_estimate'))
print("Equity Value:", val_res.get('equity_value'))
print("Shares Cr:", val_res.get('shares_in_cr') or data.get('shares_in_cr'))
print("Intrinsic Value:", val_res.get('intrinsic_value_per_share'))

wb = openpyxl.load_workbook('exports/ADANIENT_Valuation_Model.xlsx', data_only=True)
ws = wb['DCF']
print("\n=== EXCEL DCF INPUTS & INTERMEDIATES ===")
print("EBIT Y1 (I8):", ws['I8'].value)
print("NOPAT Y1 (I10):", ws['I10'].value)
print("Reinvest Y1 (I11):", ws['I11'].value)
print("FCFF Y1 (I12):", ws['I12'].value)
print("FCFF Y5 (M12):", ws['M12'].value)
print("PV FCFF Sum (D33):", ws['D33'].value)
print("Terminal Value (D29):", ws['D29'].value)
print("PV Terminal Value (D34):", ws['D34'].value)
print("Enterprise Value (D35):", ws['D35'].value)
print("Debt (D38):", ws['D38'].value)
print("Cash (D37):", ws['D37'].value)
print("Equity Value (D39):", ws['D39'].value)
print("Shares Cr (D40):", ws['D40'].value)
print("Intrinsic Value (D42):", ws['D42'].value)
print("Growth Rate (D18):", ws['D18'].value)
print("Tax Rate (D19):", ws['D19'].value)
print("WACC (D20):", ws['D20'].value)
print("Terminal g (D19 in some or D27):", ws['D27'].value)
